add superbadge model and register in admin panel
mint-o-badges/badgr-server pull request #13
Opened 2024-02-14 19:51 UTC by jona159

- add superbadge model
- register superbadges in admin panel
- endpoint to fetch superbadges in frontend

To apply the changes run: 

- ```docker-compose exec api python /badgr_server/manage.py makemigrations```
- ```docker-compose exec api python /badgr_server/manage.py migrate```

2024-02-15 11:56 UTC, timber-they requested changes

2024-02-15 11:56 UTC, timber-they commented on apps/issuer/api.py
> +    # v2_serializer_class = BadgeClassSerializerV2
This commented line doesn't make too much sense

2024-02-15 11:56 UTC, timber-they commented on apps/issuer/models.py
> +    # def delete(self, *args, **kwargs):
Why is this commented code here?

2024-02-15 11:56 UTC, timber-they commented on apps/issuer/models.py
> +    # def delete(self):
And this?

2024-02-15 11:56 UTC, timber-they commented on apps/issuer/models.py
> +    superbadge = models.ForeignKey('issuer.SuperBadge',
I don't quite understand the relationship of the super badge to issuer / badge class, maybe a comment clarifying this would be helpful?

2024-02-15 11:56 UTC, timber-they commented on apps/issuer/public_api.py
> +    # def log(self, obj):
This comment doesn't seem to make too much sense either

2024-02-15 11:56 UTC, timber-they commented on apps/issuer/serializers_v1.py
> +        # list_serializer_class = SuperBadgeBadgeSerializerV1
Same as other commented code

2024-02-15 11:56 UTC, timber-they commented on apps/issuer/serializers_v1.py
> +    id = serializers.RelatedField(queryset=BadgeClass.objects.all())
What ID is this? Why is this query set requesting all badge classes? Probably a comment clarifying this would be helpful

2024-02-15 11:56 UTC, timber-they commented on apps/issuer/serializers_v1.py
> +class SuperBadgeClassSerializerV1(serializers.Serializer):
Isn't this class defined twice with the definition before?

2024-02-15 11:56 UTC, timber-they commented on apps/issuer/serializers_v1.py
> +    badges = serializers.PrimaryKeyRelatedField(many=True, queryset=BadgeClass.objects.all(), required=False, source='cached_collects')
A comment explaining the relationship of this "primary key related field" would be helpful

2024-02-15 11:56 UTC, timber-they commented on apps/issuer/serializers_v1.py
> +        representation['badges'] = [{'name': badge.name, 'description': badge.description} for badge in instance.cached_collects()]
Is it correct that this is about "badges" and not "superbadges" or sth similar?

2024-03-05 08:44 UTC, timber-they commented
Is this PR still relevant?

2024-03-05 09:12 UTC, jona159 commented
No. I close it

2024-03-05 09:12 UTC, closed without merging