add mailhog to docker compose and use smtp email backend in local dev…
mint-o-badges/badgr-server pull request #33
Opened 2024-03-19 15:43 UTC by umut0

… with mailhog configuration

This will allow us to test Emails easily while developing. Changes nothing for production.

2024-03-20 10:24 UTC, timber-they requested changes

2024-03-20 10:24 UTC, timber-they commented on .docker/etc/settings_local.dev.py.example
> +NOUNPROJECT_API_KEY =
What is the use of this change?

2024-03-20 10:33 UTC, umut0 commented on .docker/etc/settings_local.dev.py.example
> +NOUNPROJECT_API_KEY =
accident. will fix.

2024-03-21 14:14 UTC, timber-they approved these changes

2024-03-21 14:22 UTC, merged